# Generated by Django 5.1.5 on 2025-01-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='descriotion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
