# Generated by Django 5.1.5 on 2025-01-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
