# Generated by Django 5.1.5 on 2025-01-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factus', '0003_municipality_unitmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factus.unitmeasure'),
        ),
    ]
