# Generated by Django 5.1.5 on 2025-01-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factus', '0003_cart_cartproducts_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='IVA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
