# Generated by Django 5.1.5 on 2025-01-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factus', '0005_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descriotion',
            new_name='description',
        ),
    ]
